version: "3.9"

services:
  api:
    build: .
    container_name: unreliableunicorn_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    container_name: unreliableunicorn_db
    restart: always
    environment:
      POSTGRES_DB: unreliableunicorn
      POSTGRES_USER: unicorn_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U unicorn_user -d unreliableunicorn"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
