version: "3.9"

services:
  api:
    build: .
    container_name: unreliableunicorn_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: unreliableunicorn_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-changeme}
      MYSQL_DATABASE: unreliableunicorn
      MYSQL_USER: unicorn_user
      MYSQL_PASSWORD: ${DB_PASSWORD:-changeme}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD:-changeme}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
